XXX_SAMPLE_XXX_MULTITASK-AR-FOXA1-HOXB13-GATA2_ATAC-UniBindPWM:
    dataspec: ../local/configfiles/models_dataspec/XXX_SAMPLE_XXX_MULTITASK-AR-FOXA1-HOXB13-GATA2_ATAC-UniBindPWM.yml
    config: ../local/configfiles/models_config/bpnet9_atacseq.gin
    jobfile: ../local/src/slurm_train.sh
    tasks: AR-FOXA1-HOXB13-GATA2
    summits: 
        - bed/tampere_pc_atac/XXX_SAMPLE_XXX_UniBindPWM_AR_peaks.bed
        - bed/tampere_pc_atac/XXX_SAMPLE_XXX_UniBindPWM_FOXA1_peaks.bed
        - bed/tampere_pc_atac/XXX_SAMPLE_XXX_UniBindPWM_HOXB13_peaks.bed
        - bed/tampere_pc_atac/XXX_SAMPLE_XXX_UniBindPWM_GATA2_peaks.bed
    bw: 
        - XXX_SAMPLE_XXX

